version: '3'
services:
  gemastik:
    container_name: pwnworld
    restart: always
    build:
      context: .
    working_dir: /home/ctf
    ports:
      - "10012:31337" # exposed:local
    entrypoint: /etc/run_xinetd.sh
    read_only: true
